version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tools/ui_test_config.sql:/docker-entrypoint-initdb.d/ui_test_config.sql
      - ./tools/ui_test_populate.sql:/ui_test_populate.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  bnauth:
    image: finda/bntech-bnauth:latest.arm
    build: .
    ports:
      - "8443:8443"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
  ws-client:
    build: ./ws-client/.
    image: finda/bnauth-ws-client:latest.arm
    ports:
      - "3000:3000"
    restart: always
