server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/qrekru
    username: postgres
    password: HCF39uAHAY
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

